# Site settings
title: OpenDataMine
email: opendatamine@ferric.net
description: "OpenDataMine: A Read-only API for the real world"
baseurl: ""
url: "http://opendatamine.com"

# Build settings
markdown: kramdown
permalink: pretty
